### ISSUE TITLE
Controller type not found

### ISSUE THREAD

**Issue by dreamsinspace** [react-spring/react-spring#685]
## 🐛 Bug Report

Cannot import Controller as it's not exported

## To Reproduce

This simple code demonstrates best:
```
import { Controller } from 'react-spring';

console.log(Controller) // -> Returns undefined 
```

## Expected behavior
Controller should not be undefined

## Environment

- `react-spring` v8.0.20
- `react` v16.8.6

**Comment by aleclarson** [comment]
Can you try with `react-spring@next`? Thanks! 👍

**Comment by dreamsinspace** [comment]
@aleclarson So Controller doesn't exist in 8.x.x?

**Comment by aleclarson** [comment]
It does, but I guess it's not exported from the main module. And since the package is bundled, you won't be able to get access to it. This is fixed in v9 though.

**Comment by dreamsinspace** [comment]
@aleclarson This should be mentioned somewhere in the docs I guess. Thanks for the clarification!

**Comment by dreamsinspace** [comment]
@aleclarson Just updated and `Controller` still doesn't exist. Please reopen. Cheers

**Comment by aleclarson** [comment]
Just tested it locally and it exists. Try deleting any lockfiles and `node_modules` directories.

**Comment by dreamsinspace** [comment]
@aleclarson I'll try. What I did was `npm install react-spring@next`

**Comment by dreamsinspace** [comment]
@aleclarson Tried and `Controller` still not found

**Comment by aleclarson** [comment]
Ah that's right, the Controller class is not included in the TypeScript definitions yet. I'll try to sort that out for the next beta.

**Comment by dreamsinspace** [comment]
What shall i use now as an alternative?

**Comment by aleclarson** [comment]
v9.0.0-beta.9 is out! Sorry for the delay :)
