### ISSUE TITLE
Property 'children' does not exist ... on animated(View) react-native components.

### ISSUE THREAD

**Issue by benvp** [react-spring/react-spring#752]
## 🐛 Bug Report
I guess this is a typescript issue. When wrapping a react-native component like `View` with `animated`, then typescript complains about that `children` is not a valid property for the component. The app works anyway, so this should be only a typescript thing.

![image](https://user-images.githubusercontent.com/981344/60978502-8ca72500-a331-11e9-9d87-a0a57a2d4fb6.png)

Probably somehow related to https://github.com/react-spring/react-spring/issues/508 but the merge did not fix the issue using RN.

## To Reproduce

```ts
const HelloWorld = () => {
  const AnimatedView = animated(View);
  
  // error occurs here
  return <AnimatedView>Hello World</AnimatedView>
}

```

## Expected behavior

The wrapped view should copy the original components properties.

## Environment

- `react-spring` v8.0.27
- `react-native` v0.59.8

**Comment by aleclarson** [comment]
Already fixed in v9
```sh
npm install react-spring@next
```

**Comment by aleclarson** [comment]
This actually isn't fixed in the latest beta, but it will in the next beta.

**Comment by JackCA** [comment]
I'm running into this as well.

I'm noticing https://github.com/react-spring/react-spring/issues/642 is open and am assuming that the next beta refers the beta after `34`.

Would it be possible to push the fixes independent of the other changes that have accumulated over the past 5 months?

**Comment by hieunguyendut** [comment]
@benvp Hi there, Could you able to wrap text with View component in React, As far as I know it can't be.
change 
const HelloWorld = () => {
  const AnimatedView = animated(View);
  
  // error occurs here
  return <AnimatedView>Hello World</AnimatedView>
}
to 
const HelloWorld = () => {
  const AnimatedText = animated(Text);
  
  // error occurs here
  return <AnimatedText>Hello World</AnimatedText>
}

**Comment by benvp** [comment]
I'm not sure if I understand what you mean. Can you try to describe this a bit more? The error also occurs if I wrap any react-native component inside animated

**Comment by gchumillas** [comment]
There's a weird solution to this issue. Simply write:

```ts
const AnimatedText = animated<React.ElementType<React.PropsWithChildren<TextProps>>>(Text)
```

But this is an insane workaround. I better move to JavaScript.

**Comment by aleclarson** [comment]
Please try with [the latest canary](https://spectrum.chat/react-spring/general/try-the-new-v9-canary~c5cad1eb-c6ff-4b40-9a10-76d368c3e404). 👍

**Comment by benvp** [comment]
> There's a weird solution to this issue. Simply write:
> 
> ```ts
> const AnimatedText = animated<React.ElementType<React.PropsWithChildren<TextProps>>>(Text)
> ```
> 
> But this is an insane workaround. I better move to JavaScript.
> 
> **UPDATE:**
> 
> It's not necessary to use `React.PropsWithChildren`. You can simply write:
> 
> ```ts
> const AnimatedText = animated<React.ElementType<TextProps>>(Text)
> ```
> 
> and that's a reasonable approach.

This doesn't really work for me. React.ElementType does not seem to exist in the React Types for typescript.

**Comment by aleclarson** [comment]
Fixed in `9.0.0-rc.2` (#985)

**Comment by viniaxt** [comment]
I'm still having the same error. Tried to use 9.0.0-rc.2 and had some strange errors in react native:

1. react spring dependency asked for react-dom, wich that doesn't make sense in react native

2. Property children does not exist...

Even adding react-dom dependency to our project, we still have error numbe 2.

**Comment by aleclarson** [comment]
@viniaxt TypeScript version plz

The `react-spring` package contains every supported platform. You can use `@react-spring/native` to avoid the peer dependency complaints.

**Comment by viniaxt** [comment]
TypeScript 3.8.3

Being honest with you, i didn't know that react-spring had a specific package for react-native. I think it would be better if it's been specified in documentation.Will try now with @react-spring/native

**Comment by CyrusZei** [comment]
it is a little bit sad that there is not much documentation on the react-native part 😞  As soon as I understand how this works with React-native I will make a PR to the documentation and add each step.

**Comment by MrCreeper1008** [comment]
Same issue on TypeScript 4.1.3 with `@react-spring/native`.

**Comment by jimmi-joensson** [comment]
I am experiencing this issue with `typescript@3.4.5` and `react-spring/native@9.0.0`

**Comment by joshuaellis** [comment]
> I am experiencing this issue with `typescript@3.4.5` and `react-spring/native@9.0.0`

@jimmi-joensson If you want this bug to be looked at please open a new issue and follow the template carefully (please don't forget the reproduction, we won't be working on it otherwise). This issue is closed and will not be reopened.

Alternatively, if you want it fixed quick, I always welcome PRs ⭐
