### ISSUE TITLE
Custom prop names inside useTransition. Typescript throws errors

### ISSUE THREAD

**Issue by jwmann** [react-spring/react-spring#821]
In one of the examples for `useTransition` it uses a custom prop name.
I believe it was `imageHeight` and they destructured that prop from `props` to use in the `transitions.map()`.
https://codesandbox.io/embed/vqpqx5vrl0

I'm using Typescript so when I use the same technique I get some errors because of course `imageHeight` is not a real CSS property.

`Object literal may only specify known properties`

Is there a way to add my own type definitions to the `useTransition` values?

**Comment by aleclarson** [comment]
The beta for v9 should fix this for you.

```
npm install react-spring@next
```

**Comment by jwmann** [comment]
Thanks @aleclarson 
I updated to the latest beta as you suggested and I still get the same error.
I think I need to add my custom type definitions somewhere, I just don't know where/how to add them.

**Comment by aleclarson** [comment]
Can you create a git repo that demonstrates the issue? You shouldn't need custom typedefs.

**Comment by jwmann** [comment]
@aleclarson I kid you not I spent like 20 minutes building a codesandbox and my VSCode finally updated with the proper Typescript.

No more errors now. 
Thanks again.
